### ISSUE TITLE
Project accessibility

### ISSUE THREAD

**Issue by LiamKeeble** [LiamKeeble/MinorityReport#7]
I was thinking I might make this GitHub public so that when it is time to present our poster we can just share the link to the GitHub rather than pre-register again. @caitlin91 What do you think?

**Comment by caitlin91** [comment]
Oh thought! @LiamKeeble API key is in the script...assume it's buried deep enough it's not a problem? Or we could both save them in the folder above on our own PCs and use a referential path in the R script?

**Comment by LiamKeeble** [comment]
I've removed it for now
